### PR TITLE
milkyway <> skip integration endpoints

### PR DESCRIPTION
**Pull request by JSHan94**
To automate the password update process in case of a password breach of the authorized endpoint of a node, adding an index field for pwd salt generation.

- add index field for authorized user
- milkyway setup for skip-api integration

### CODE REVIEW

**Comment by Vritra4** [comment]
just `index` sounds ambiguous

**Comment by JSHan94** [comment]
@Vritra4 how about saltIndex?

**Review by dhfang — APPROVED** [review]
Looks good to me

**Comment by Vritra4** [comment]
I prefer an object as a value because it's easy to extend. If you think there's no chance to extend or update something between us and skip, make it ready for review

**Review by ALPAC-4 — APPROVED** [review]

**Pull request merged**
